---
title: "Reporte"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
    toc_depth: 5
    includes:
      in_header: logo.html
---

```{r, librerias,include=FALSE, echo=FALSE}
library(pacman)
library(ggplot2)
library(plotly)
library(gganimate)
library(gifski)
library(mapview)
library(sf)
library(rgdal)
library(maptools)
library(gridExtra)
library(data.table)
library(DT)
library(leaflet)

```



#**Introducción**

#**Resultados**

###**Mapa de Red**

```{r, include=FALSE, leerCapas, echo=FALSE}
 
flirs <- st_read("Mapas/flirs.shp")
rgbs <- st_read("Mapas/rgbs.shp")
puntos <-st_read("Mapas/COT04010 Puntos.shp")
redes <- st_read("Mapas/LST-OVI-73510-COT.shp")

```


```{r mapa1, echo=FALSE}
img<- rgbs$RelPath
mapview::mapview(list(puntos, redes),labels=F, map.types = "Esri.WorldImagery")
```

```{r mapa2, echo=FALSE}
img<- rgbs$RelPath
mapview::mapview(list(flirs,rgbs),labels=F, map.types = "Esri.WorldImagery")
```


###**Informe de Torres**

```{r, datosEstados, echo=FALSE}

datatable(rgbs)
```